import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Shared/Navbar'
import NextTopLoader from 'nextjs-toploader'
import Footer from '@/Components/Shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>

<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
/>
</head>
      <NextTopLoader color="red" speed={200}/>
      <body className={inter.className}>
      <Navbar/>

        {children}
        <Footer/>

        </body>
    </html>
  )
}
